"""init

Revision ID: 0f27d6716f68
Revises: 22efb6895371
Create Date: 2026-05-28 17:45:44.060899

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f27d6716f68"
down_revision: Union[str, Sequence[str], None] = "22efb6895371"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("line1", sa.String(length=100), nullable=False),
        sa.Column("city", sa.String(length=255), nullable=False),
        sa.Column("postal_code", sa.Integer(), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("city"),
    )
    op.create_index(
        op.f("ix_addresses_employee_id"), "addresses", ["employee_id"], unique=False
    )
    op.create_index(op.f("ix_addresses_id"), "addresses", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_addresses_id"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_employee_id"), table_name="addresses")
    op.drop_table("addresses")
    # ### end Alembic commands ###
