"""init

Revision ID: 488457c9908f
Revises: 0f27d6716f68
Create Date: 2026-05-29 10:19:01.752176

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "488457c9908f"
down_revision: Union[str, Sequence[str], None] = "0f27d6716f68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
