"""added status

Revision ID: 488e29cc718c
Revises: 69c0cc18202b
Create Date: 2026-06-10 17:06:51.957256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488e29cc718c'
down_revision: Union[str, Sequence[str], None] = '69c0cc18202b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


STATUS_ENUM=sa.Enum('Active', 'Inactive', 'Probation', name='employeestatus')
def upgrade() -> None:

    """Upgrade schema."""
    STATUS_ENUM.create(op.get_bind(), checkfirst=True)
    #
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('status', STATUS_ENUM, server_default='Active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'status')
    # ### end Alembic commands ###
