"""init

Revision ID: 798dcf7ed0a3
Revises: 488457c9908f
Create Date: 2026-05-29 16:01:42.758414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "798dcf7ed0a3"
down_revision: Union[str, Sequence[str], None] = "488457c9908f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees", sa.Column("password_hash", sa.String(length=255), nullable=True)
    )
    op.execute(
        "UPDATE employees SET password_hash= 'placeholder' WHERE password_hash IS NULL"
    )
    op.alter_column("employees", "password_hash", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "password_hash", nullable=False)
    # ### end Alembic commands ###
