"""junction table

Revision ID: 90e1d4fb38ba
Revises: 80e8db80f2d3
Create Date: 2026-06-01 01:37:26.239825

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "90e1d4fb38ba"
down_revision: Union[str, Sequence[str], None] = "80e8db80f2d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
