"""init

Revision ID: e6c283b6f4f4
Revises: 7841dd81db24
Create Date: 2026-06-01 00:42:57.997911

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e6c283b6f4f4"
down_revision: Union[str, Sequence[str], None] = "7841dd81db24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
